const defaultData = [
    [
        "1ο Γυμνάσιο Βριλησσίων",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Ωρολόγιο πρόγραμμα διδασκόντων"
    ],
    [
        "Σε ισχύ: 20-10-25",
        null,
        null,
        "ΔΕΥΤΕΡΑ",
        null,
        null,
        null,
        null,
        null,
        null,
        "ΤΡΙΤΗ",
        null,
        null,
        null,
        null,
        null,
        null,
        "ΤΕΤΑΡΤΗ",
        null,
        null,
        null,
        null,
        null,
        null,
        "ΠΕΜΠΤΗ",
        null,
        null,
        null,
        null,
        null,
        null,
        "ΠΑΡΑΣΚΕΥΗ"
    ],
    [
        "α/α",
        "Διδάσκων",
        "ΠΕ",
        "1η",
        "2η",
        "3η",
        "4η",
        "5η",
        "6η",
        "7η",
        "1η",
        "2η",
        "3η",
        "4η",
        "5η",
        "6η",
        "7η",
        "1η",
        "2η",
        "3η",
        "4η",
        "5η",
        "6η",
        "7η",
        "1η",
        "2η",
        "3η",
        "4η",
        "5η",
        "6η",
        "7η",
        "1η",
        "2η",
        "3η",
        "4η",
        "5η",
        "6η",
        "7η"
    ],
    [
        1,
        "ΣΥΡΜΑ ΕΥΑΓΓΕΛΙΑ",
        "ΠΕ02",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Α1\nΝέΛ"
    ],
    [
        2,
        "ΜΟΥΡΤΟΠΟΥΛΟΥ ΜΑΡΙΑ",
        "ΠΕ11",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Α4\nΓμν",
        "Α2\nΓμν",
        null,
        null,
        null,
        "Γ4\nΓμν",
        "Α3\nΓμν",
        "Γ1\nΓμν",
        null,
        null,
        null,
        null,
        null,
        null,
        "Α1\nΓμν",
        "Γ1\nΓμν"
    ],
    [
        3,
        "ΠΑΠΑΔΟΠΟΥΛΟΥ ΧΡΥΣΑ",
        "ΠΕ01",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Α4\nΘρσ",
        "Α3\nΘρσ",
        null,
        "Γ2\nΘρσ",
        "Α2\nΘρσ",
        null,
        null,
        null,
        "Γρ",
        "Γ4\nΘρσ",
        "Α1\nΘρσ",
        "Β1\nΘρσ",
        null,
        null,
        null,
        "Γ2\nΘρσ",
        "Α3\nΘρσ",
        "Γ1\nΘρσ"
    ],
    [
        4,
        "ΜΑΚΡΗ ΜΑΡΙΑ",
        "ΠΕ02",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γ4\nΑχΓλ",
        "Γρ",
        "Γ3\nΑχΚμ",
        "Β3\nΓλώ",
        "Β3\nΓλώ",
        null,
        null,
        "Γ1\nΑχΚμ",
        "Β2\nΙστ",
        "Γ1\nΑχΓλ",
        null,
        null,
        null,
        null,
        "Β3\nΙστ",
        "Β2\nΓλώ",
        "Β2\nΓλώ"
    ],
    [
        5,
        "ΠΑΠΑΔΟΠΟΥΛΟΥ ΑΝΑΣΤΑΣΙΑ",
        "ΠΕ02",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γ4\nΑχΚμ",
        "Γ2\nΑχΚμ",
        null,
        "Γ3\nΝέΛ",
        "Γ4\nΝέΛ",
        "Β1\nΑχΚμ",
        "Β4\nΓλώ",
        "Β4\nΓλώ",
        "Γρ",
        "Α4\nΑχΚμ",
        "Β2\nΑχΚμ",
        null,
        null,
        null,
        null,
        null,
        "Γ4\nΑχΚμ",
        "Γ2\nΑχΚμ",
        "Α3\nΑχΚμ"
    ],
    [
        6,
        "ΔΙΑΚΟΥΜΗ ΙΩΑΝΝΑ",
        "ΠΕ02",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γ3\nΙστ",
        "Β4\nΑχΚμ",
        "Γ1\nΝέΛ",
        null,
        "Α1\nΙστ",
        "Β3\nΑχΚμ",
        null,
        "Γ3\nΙστ",
        "Γ2\nΝέΛ",
        "Γ4\nΙστ",
        "Γρ",
        null,
        null,
        null,
        "Α2\nΙστ",
        "Γ1\nΓλώ",
        "Γ1\nΓλώ"
    ],
    [
        7,
        "ΓΕΡΟΝΤΑ ΚΩΝΣΤΑΝΤΙΝΑ",
        "ΠΕ02",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Α2\nΝέΛ",
        "Β1\nΝέΛ",
        null,
        "Β1\nΑχΓλ",
        "Β2\nΝέΛ",
        "Α3\nΝέΛ",
        null,
        "Β2\nΑχΓλ",
        "Β1\nΝέΛ",
        "Α2\nΝέΛ",
        "Α2\nΑχΓλ",
        null,
        null,
        null,
        null,
        "Α3\nΓλώ",
        "Α2\nΑχΓλ",
        null,
        "Α1\nΑχΓλ",
        "Α2\nΑχΚμ"
    ],
    [
        8,
        "ΒΕΝΔΡΑ ΠΑΝΑΓΙΩΤΑ",
        "ΠΕ02",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Α3\nΙστ",
        "Α4\nΙστ",
        null,
        "Β4\nΑχΓλ",
        "Α3\nΑχΓλ",
        "Γ1\nΙστ",
        null,
        "Α2\nΓλώ",
        "Α2\nΓλώ",
        "Α4\nΑχΓλ",
        "Α3\nΑχΓλ",
        null,
        null,
        null,
        null,
        "Γ4\nΓλώ",
        "Γ4\nΓλώ",
        "Β4\nΑχΓλ",
        null,
        "Α4\nΙστ"
    ],
    [
        9,
        "ΚΛΑΔΗ ΠΗΓΗ",
        "ΠΕ02",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Α4\nΓλώ",
        "Α1\nΑχΚμ",
        "Γρ",
        "Γ2\nΑχΓλ",
        "Β4\nΝέΛ",
        "Β4\nΙστ",
        null,
        "Α1\nΓλώ",
        "Α1\nΓλώ",
        null,
        "Α1\nΑχΚμ",
        "Α4\nΝέΛ",
        null,
        null,
        "Α4\nΓλώ",
        null,
        "Α4\nΓλώ"
    ],
    [
        10,
        "ΓΚΟΥΒΑΣ ΑΝΑΣΤΑΣΙΟΣ",
        "ΠΕ03",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β2\nΜαθ",
        "Α2\nΜαθ",
        "Α3\nΜαθ",
        "Γρ",
        null,
        null,
        null,
        "Α4\nΜαθ",
        "Α3\nΜαθ",
        null,
        null,
        "Α2\nΜαθ",
        "Β2\nΜαθ",
        "Α1\nΜαθ",
        "Α1\nΜαθ",
        "Α4\nΜαθ",
        "Α3\nΜαθ"
    ],
    [
        11,
        "ΜΠΟΛΕΤΗ ΚΩΣΤΟΥΛΑ",
        "ΠΕ03",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β4\nΦυσ",
        "Β3\nΜαθ",
        "Γ4\nΜαθ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β3\nΜαθ",
        null,
        "Β4\nΜαθ",
        "Γ1\nΜαθ",
        "Β4\nΜαθ",
        "Β3\nΜαθ",
        null,
        "Γ1\nΜαθ",
        "Γ4\nΜαθ"
    ],
    [
        12,
        "ΧΟΥΤΟΥ ΧΡΥΣΑ",
        "ΠΕ03",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β1\nΜαθ",
        "Γ2\nΜαθ",
        "Γ3\nΜαθ",
        null,
        null,
        "Γ2\nΜαθ",
        "Γρ",
        "Γ3\nΜαθ",
        "Β1\nΜαθ"
    ],
    [
        13,
        "ΒΑΖΟΥΡΑ ΕΥΑΓΓΕΛΙΑ",
        "ΠΕ04.01",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γ1\nΦσκ",
        "Γ3\nΦσκ",
        "Γ2\nΦσκ",
        null,
        null,
        null,
        null,
        "Γ2\nΦσκ",
        "Γ1\nΦσκ",
        "Γ4\nΦσκ",
        "Γ4\nΦσκ",
        "Γρ",
        "Γ3\nΦσκ",
        "Α3\nΦσκ",
        "Α2\nΦσκ"
    ],
    [
        14,
        "ΓΚΙΖΕΛΗ ΙΟΥΛΙΑ",
        "ΠΕ04.04",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β2\nΧημ",
        "Α1\nΒιο",
        null,
        "Β1\nΦυσ",
        "Α3\nΒιο",
        null,
        null,
        "Β2\nΦυσ",
        "Γ2\nΒιο",
        null,
        "Α2\nΒιο",
        "Α4\nΒιο",
        "Β1\nΧημ",
        "Α2\nΓεω",
        "Β4\nΧημ"
    ],
    [
        15,
        "ΚΑΡΑΓΙΑΝΝΗ ΘΕΟΦΑΝΩ",
        "ΠΕ04.04",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β3\nΓεω",
        null,
        "Β4\nΒιο",
        "Γ1\nΧημ",
        "Γ2\nΧημ",
        null,
        null,
        null,
        null,
        null,
        "Β4\nΓεω",
        "Β3\nΓεω",
        "Β1\nΒιο",
        "Β2\nΓεω",
        "Β2\nΒιο",
        "Β4\nΓεω",
        "Β3\nΒιο",
        null,
        "Β1\nΓεω",
        "Γ4\nΧημ"
    ],
    [
        16,
        "ΚΑΝΕΛΟΠΟΥΛΟΥ ΚΩΝΣΤΑΝΤΙΝΑ",
        "ΠΕ05",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β1Γαλ Γαλ",
        "Α3\nΓαλ",
        "Α1Γαλ Γαλ",
        null,
        null,
        null,
        null,
        "Γ2\nΓαλ",
        "Α4\nΓαλ",
        "Β3\nΓαλ",
        null,
        "Β4\nΓαλ",
        "Γ3\nΓαλ",
        null,
        null,
        "Α1Γαλ Γαλ",
        "Β1Γαλ Γαλ",
        "Α2\nΓαλ",
        null,
        "Β3\nΓαλ"
    ],
    [
        17,
        "ΑΠΟΣΤΟΛΟΠΟΥΛΟΥ ΝΙΚΟΛΕΤΑ",
        "ΠΕ06",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β2\nΑγγ",
        "Β1\nΑγγ",
        "Α2\nΑγγ",
        null,
        "Β1\nΑγγ",
        "Γρ",
        "Γ3\nΑγγ",
        null,
        "Α1\nΑγγ",
        "Γ4\nΑγγ",
        "Α2\nΑγγ",
        null,
        null,
        null,
        "Β2\nΑγγ",
        "Β3\nΑγγ",
        "Γ2\nΑγγ"
    ],
    [
        18,
        "ΑΓΟΡΗ ΜΥΡΤΩ",
        "ΠΕ06",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Α3\nΑγγ",
        "Α3\nΑγγ"
    ],
    [
        19,
        "ΓΟΝΙΟΥ ΚΑΤΕΡΙΝΑ",
        "ΠΕ07",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β1Γερ Γερ",
        "Γ1\nΓερ",
        "Α1Γερ Γερ",
        "Γρ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γ1\nΓερ",
        "Α1Γερ Γερ",
        "Β1Γερ Γερ"
    ],
    [
        20,
        "ΜΠΑΛΩΜΕΝΟΥ ΚΑΤΕΡΙΝΑ",
        "ΠΕ08",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γρ",
        "Γ4\nΚαλ",
        "Α4\nΚαλ",
        "Α1\nΕργ",
        "Α3\nΕργ",
        "Β3\nΚαλ",
        null,
        "Β1\nΚαλ",
        "Γ1\nΚαλ",
        null,
        null,
        null,
        null,
        null,
        "Α4\nΕργ",
        "Β2\nΕργ",
        "Γ3\nΚαλ"
    ],
    [
        21,
        "ΧΑΣΙΩΤΗ ΚΑΛΛΙΟΠΗ",
        "ΠΕ11",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Β2\nΓμν",
        "Β3\nΓμν",
        null,
        null,
        null,
        null,
        null,
        null,
        "Β4\nΓμν",
        "Β2\nΓμν",
        null,
        null,
        null,
        null,
        "Β1\nΓμν",
        "Γρ",
        "Γ3\nΓμν"
    ],
    [
        22,
        "ΒΑΣΙΛΟΓΙΑΝΝΗ ΕΥΑΓΓΕΛΙΑ",
        "ΠΕ78",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γ2\nΚπα",
        null,
        "Α2ΠΤ\nΟικ",
        "Γ3\nΚπα",
        "Α4ΠΤ\nΟικ",
        null,
        null,
        "Γ4\nΚπα",
        "Γ1\nΚπα",
        "Γ2\nΚπα",
        null,
        "Γ3\nΚπα",
        "Α4ΠΤ\nΟικ",
        null,
        "Γ2\nΚπα",
        "Γ3\nΚπα",
        "Α1ΠΤ\nΟικ",
        null,
        "Γρ"
    ],
    [
        23,
        "ΠΟΥΛΕΤΣΟΣ ΑΝΔΡΕΑΣ",
        "ΠΕ79.01",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γ3\nΕργ",
        "Β1\nΜσκ",
        "Α2\nΜσκ",
        "Γρ",
        null,
        null,
        null,
        null,
        "Α1\nΜσκ",
        "Γ3\nΜσκ",
        "Γρ",
        "Α3\nΜσκ",
        "Γ2\nΕργ",
        null,
        null,
        null,
        "Β3\nΜσκ",
        "Α4\nΜσκ",
        "Β2\nΜσκ"
    ],
    [
        24,
        "ΜΑΛΙΔΕΡΟΥ ΕΛΕΝΗ",
        "ΠΕ83",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γ2ΠΤ\nΤχν",
        null,
        "Γ4ΠΤ\nΤχν",
        null,
        "Α1ΠΤ\nΤχν",
        "Α4ΠΤ\nΤχν",
        null,
        "Γ3ΠΤ\nΤχν",
        "Β1ΠΤ\nΤχν",
        "Γ4ΠΤ\nΤχν",
        "Α3ΠΤ\nΤχν",
        null,
        null,
        "Γ3ΠΤ\nΤχν",
        "Γ2ΠΤ\nΤχν",
        null,
        "Β1ΠΤ\nΤχν",
        null,
        "Α1ΠΤ\nΤχν"
    ],
    [
        25,
        "ΠΙΤΟΥ ΜΑΡΙΑ",
        "ΠΕ86",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Α2ΠΤ\nΠλρ2 Πλρ",
        null,
        "Α4ΠΤ\nΠλρ2 Πλρ",
        "Α1ΠΤ\nΠλρ1 Πλρ",
        "Α4ΠΤ\nΠλρ1 Πλρ",
        null,
        null,
        null,
        null,
        "Α3ΠΤ\nΠλρ1 Πλρ",
        "Α4ΠΤ\nΠλρ2 Πλρ",
        "Β4ΠΤ\nΠλρ Πλρ",
        null,
        null,
        "Α1ΠΤ\nΠλρ2 Πλρ",
        null,
        "Β4ΠΤ\nΠλρ Πλρ",
        "Α1ΠΤ\nΠλρ1 Πλρ"
    ],
    [
        26,
        "ΠΡΕΝΤΖΑ ΑΡΕΤΗ",
        "ΠΕ86",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Γ1\nΠλρ Πλρ",
        "Γ2ΠΤ\nΠλρ Πλρ",
        null,
        "Γ4ΠΤ\nΠλρ Πλρ",
        null,
        null,
        null,
        "Β3\nΠλρ Πλρ",
        "Γ3ΠΤ\nΠλρ Πλρ",
        "Β1ΠΤ\nΠλρ Πλρ",
        "Γ4ΠΤ\nΠλρ Πλρ",
        null,
        null,
        null,
        "Γ3ΠΤ\nΠλρ Πλρ",
        "Γ2ΠΤ\nΠλρ Πλρ",
        "Γρ",
        "Β1ΠΤ\nΠλρ Πλρ"
    ]
];

const replacements = {
    'ΑχΓλ': 'Αρχαία Γλώσσα',
    'ΑρΓΛ': 'Αρχαία Γλώσσα',
    'Αρχ Γλ': 'Αρχαία Γλώσσα',
    'Γαλ': 'Γαλλικά',
    'Γερ': 'Γερμανικά',
    'Μαθ': 'Μαθηματικά',
    'Εργ': 'Εργαστήριο Δεξιοτήτων',
    'Γλώ': 'Γλώσσα',
    'ΝέΛ': 'Λογοτεχνία',
    'Αγγ': 'Αγγλικά',
    'ΑχΚμ': 'Αρχαία Κείμενα',
    'Γεω': 'Γεωγραφία',
    'Ιστ': 'Ιστορία',
    'Καλ': 'Εικαστικά',
    'Θρσ': 'Θρησκευτικά',
    'Βιο': 'Βιολογία',
    'Φσκ': 'Φυσική',
    'Γμν': 'Γυμναστική',
    'Οικ': 'Οικιακή Οικονομία',
    'Πλρ': 'Πληροφορική',
    'ΠλρΠλρ': 'Πληροφορική',
    'Πλρ2Πλρ': 'Πληροφορική',
    'Πλρ1Πλρ': 'Πληροφορική',
    'Τχν': 'Τεχνολογία',
    'Μσκ': 'Μουσική',
    'Χημ': 'Χημεία',
    'Φυσ': 'Φυσική',
    'Κπα': 'Κοινωνική και Πολιτική Αγωγή',


};

const backgroundImages = {
    'Αρχαία Γλώσσα': 'ancient.png',
    'Μαθηματικά': 'math.png',
    'Γαλλικά': 'french.png',
    'Αρχαία Κείμενα': 'odyssey.png',
    'Ιστορία': 'history.png',
    'Εικαστικά': 'art.png',
    'Λογοτεχνία': 'literature.png',
    'Αγγλικά': 'english.png',
    'Θρησκευτικά': 'religion.png',
    'Γυμναστική': 'sports.png',
    'Πληροφορική': 'informatics.png',
    'Τεχνολογία': 'informatics.png',
    'Γλώσσα': 'language.png',
    'Μουσική': 'music.png',
    'Γεωγραφία': 'geography.png',
    'Φυσική': 'physics.png',
    'Βιολογία': 'biology.png',
    'Εργαστήριο': 'workshop.png',
    'Χημεία': 'chemistry.png',
    'Γερμανικά': 'german.png',
    'Κοινωνική και Πολιτική Αγωγή': 'kpa.png',

}; 