const defaultData = [
    [
        "1ο Γυμνάσιο Βριλησσίων",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Ωρολόγιο πρόγραμμα διδασκόντων",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "Σε ισχύ: 14/9/26",
        null,
        null,
        "ΔΕΥΤΕΡΑ",
        null,
        null,
        null,
        null,
        null,
        "ΤΡΙΤΗ",
        null,
        null,
        null,
        null,
        null,
        "ΤΕΤΑΡΤΗ",
        null,
        null,
        null,
        null,
        null,
        "ΠΕΜΠΤΗ",
        null,
        null,
        null,
        null,
        null,
        "ΠΑΡΑΣΚΕΥΗ",
        null,
        null,
        null,
        null,
        null
    ],
    [
        "α/α",
        "Ονοματεπώνυμο",
        "ΠΕ",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "1",
        "2",
        "3",
        "4",
        "5",
        null
    ],
    [
        "1",
        "ΣΥΡΜΑ ΕΥΑΓΓΕΛΙΑ",
        "ΠΕ02",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "2",
        "ΜΟΥΡΤΟΠΟΥΛΟΥ ΜΑΡΙΑ",
        "ΠΕ11",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "3",
        "ΓΟΥΡΓΑΡΗ ΕΥΓΕΝΙΑ",
        "ΠΕ02",
        "Α4 ΑρχΓλ",
        "Α3 ΑρχΓλ",
        "Β2 ΑρχΓλ",
        "Γ1 ΑρχΓλ",
        null,
        null,
        "Γ1 Γλω",
        "Α2 Γλω",
        "Β1 ΑρχΓλ",
        null,
        null,
        null,
        "Α3 Ιστ",
        null,
        "Α2 ΝεΛ",
        "Α4 Ιστ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "4",
        "ΔΙΑΚΟΥΜΗ ΙΩΑΝΝΑ",
        "ΠΕ02",
        "Β1 ΑρχΚμ",
        "Β2 ΑρχΚμ",
        null,
        "Α1 Ιστ",
        null,
        null,
        "Γ3 Γλω",
        "Γ4 Γλω",
        "Γ1 Ιστ",
        "Γ2 Ιστ",
        null,
        null,
        null,
        "Α2 Ιστ",
        "Γ3 Γλω",
        "Γ4 Γλω",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "5",
        "ΜΑΚΡΗ ΜΙΡΑΝΤΑ",
        "ΠΕ02",
        "Β2 Γλω",
        "Γ2 ΑρχΓλ",
        null,
        "Γ3 ΑρχΚμ",
        null,
        null,
        "Γ4 ΑρχΓλ",
        "Γ3 ΑρχΓλ",
        "Γ2 ΑρΚμ",
        "Β4 Ιστ",
        null,
        null,
        "Γ3 ΑρχΚμ",
        "Γ2 ΑρχΓλ",
        "Β2 Ιστ",
        "Β4 Γλω",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "6",
        "ΝΤΟΥΜΑΖΙΟΥ ΠΑΝΤΟΥΛΑ",
        "ΠΕ02",
        "Α3 Γλω",
        "Β3 ΑρχΓλ",
        "Β4 ΑρχΚμ",
        null,
        null,
        null,
        "Β3 ΑρχΚμ",
        "Β4 ΑρχΓλ",
        "Α4 Γλω",
        "Α3 Νελ",
        null,
        null,
        null,
        "Β4 ΑρχΚμ",
        "Α4 ΝεΛ",
        "Β3 ΑρχΓλ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "7",
        "ΠΑΠΑΝΙΚΟΛΑΟΥ ΑΛΕΞΑΝΔΡΑ",
        "ΠΕ02",
        "Γ4 ΑρχΚμ",
        "Β4 ΝεΛ",
        "Α4 Γλω",
        "Β3 Γλω",
        null,
        null,
        "Α2 ΑρχΓλ",
        "Α1 ΑρχΓλ",
        "Β3 ΑρχΚμ",
        "Β1 Γλω",
        null,
        null,
        "Α1 ΑρχΚμ",
        "Γ4 ΑρχΚμ",
        "Γ1 ΝεΛ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "8",
        "ΡΙΖΟΥ ΦΑΙΔΩΡΑ",
        "ΠΕ02",
        "Γ2 Γλω",
        "Α1 Γλω",
        "Γ1 ΝεΛ",
        "Β2 ΝεΛ",
        null,
        null,
        "B2 ΝεΛ",
        "Γ2 ΝεΛ",
        "Α2 ΑρχΚμ",
        "Β3 Ιστ",
        null,
        null,
        "Α4 ΑρχΚμ",
        "Β1 ΝεΛ",
        "Γ2 Γλω",
        "Γ1 ΝεΛ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "9",
        "ΓΚΟΥΒΑΣ ΑΝΑΣΤΑΣΙΟΣ",
        "ΠΕ03",
        "Α2 Μαθ",
        null,
        "Α1 Μαθ",
        "Β4 Μαθ",
        null,
        null,
        "Β4 Μαθ",
        "Γ1 Μαθ",
        "Β2 Μαθ",
        "Α1 Φσκ",
        null,
        null,
        "Β4 Μαθ",
        "Γ1 Μαθ",
        "Β4 Μαθ",
        "Α1 Μαθ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "10",
        "ΜΠΟΛΕΤΗ ΚΩΣΤΟΥΛΑ",
        "ΠΕ03",
        "Β3 Μαθ",
        "Γ4 Μαθ",
        "Γ3 Μαθ",
        null,
        null,
        null,
        "Γ2 Μαθ",
        "Β3 Φσκ",
        "Γ4 Μαθ",
        "Γ3 Μαθ",
        null,
        null,
        "Γ2 Μαθ",
        null,
        "Β3 Μαθ",
        "Γ3 Μαθ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "11",
        "ΓΚΙΖΕΛΗ ΙΟΥΛΙΑ",
        "ΠΕ04.04",
        "Β4 Φσκ",
        "Β1 Φσκ",
        "Β3 Χημ",
        "Α2 Γεω",
        null,
        null,
        "Α1 Γεω",
        "Β2 Φσκ",
        "Γ3 Βιο",
        "Γ1 Βιο",
        null,
        null,
        "Β1 Χημ",
        "Α4 Βιο",
        null,
        "Α3 Βιο",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "12",
        "ΚΑΡΑΓΙΑΝΝΗ ΘΕΟΦΑΝΩ",
        "ΠΕ04.04",
        "Γ3 Φσκ",
        "Γ1 Χημ",
        "Γ4 Φσκ",
        "Γ2 Χημ",
        null,
        null,
        "Α4 Γεω",
        "Β1 Βιο",
        null,
        "Γ4 Χημ",
        null,
        null,
        "Γ4 Φσκ",
        "Β2 Βιο",
        "Γ4 Βιο",
        "Γ2 Φσκ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "13",
        "ΧΑΤΖΗΜΑΝΩΛΗ ΕΛΕΝΗ",
        "ΠΕ04.05",
        null,
        "Α2 Φσκ",
        "Α3 Φσκ",
        "Β1 Γεω",
        null,
        null,
        "Α3 Μαθ",
        "Α4 Μαθ",
        "Α3 Γεω",
        "Α4 Φσκ",
        null,
        null,
        "Β2 Γεω",
        "Β3 Γεω",
        "Β1 Μαθ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "14",
        "ΠΟΥΛΕΤΣΟΣ ΑΝΔΡΕΑΣ",
        "ΠΕ79.01",
        "Γ1 Μσκ",
        "Γ3 Μσκ",
        "Γ2 Μσκ",
        "Γ4 Μσκ",
        null,
        null,
        "Α2 Μσκ",
        null,
        "Β4 Μσκ",
        "Β2 Μσκ",
        null,
        null,
        null,
        "Α1 Μσκ",
        "Α3 Μσκ",
        "Β1 Μσκ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "15",
        "ΠΙΤΟΥ ΜΑΡΙΑ",
        "ΠΕ86",
        "Α1 Πλρ",
        null,
        "Α2 Πλρ",
        "Α4 Πλρ",
        null,
        null,
        "Β1 Πλρ",
        "Α3 Πλρ",
        "Α1 Πλρ",
        "Α2 Πλρ",
        null,
        null,
        "Β3 Πλρ",
        "Α3 Πλρ",
        null,
        "Α2 Πλρ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "16",
        "ΓΡΗΓΟΡΙΟΥ ΕΥΦΗΜΙΑ",
        "ΠΕ 88.04",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Α2 Τχν",
        "Γ3 Τχν",
        "Α1 Τχν",
        "Β2 Τχν",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "17",
        "ΓΙΑΝΝΑΚΟΥ ΚΥΡΙΑΚΗ",
        "ΠΕ02",
        "Β2 Γλω",
        "Β3 Αρχ Γλ",
        "Α4 Γλω",
        "Γ1 ΑρχΓλ",
        null,
        null,
        "Α2 ΑρχΓλ",
        "Β4 ΑρχΓλ",
        "Β1 ΑρχΓλ",
        "Α3 ΝεΛ",
        null,
        null,
        "Α1 ΑρχΚμ",
        "Β1 ΝεΛ",
        "Γ1 ΝεΛ",
        "Β4 Γλω",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "18",
        "ΖΑΖΟΣ ΧΡΥΣΟΣΤΟΜΟΣ",
        "ΠΕ03",
        "Α2 Μαθ",
        "Α4 Μαθ",
        "Α1 Μαθ",
        "Α3 Μαθ",
        null,
        null,
        "Β4 Μαθ",
        "Α4 Μαθ",
        "Β2 Μαθ",
        "Γ3 Μαθ",
        null,
        null,
        "Β4 Μαθ",
        "Γ1 Μαθ",
        "Β3 Μαθ",
        "Α1 Μαθ",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        "19",
        "ΚΟΝΤΟΠΟΥΛΟΥ ΜΑΡΙΑ",
        "ΠΕ04.01",
        "Γ3 Φσκ",
        "Α2 Φσκ",
        "Α3 Φσκ",
        "Β1 Γεω",
        null,
        null,
        "Α1 Γεω",
        "Β2 Φσκ",
        "Γ3 Βιο",
        "Α4 Φσκ",
        null,
        null,
        "Β1 Χημ",
        "Β3 Γεω",
        null,
        "Α3 Βιο",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
    ]
];
